# -*- coding: utf-8 -*-
"""Data Type.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EpPrWb7e6SnHbxKhBrKMBAOfn3Mvo8-v
"""

#tipe data Boolean
print(True)

#tipe data String
print("Ayo belajar Python")
print('belajar Python Sangat Mudah')

#tipe data Integer
print(20)

#tipe data Float
print(3.14)

#tipe data Hexadecimal
print(0x9a)

#tipe data Complex
print(5j)

#tipe data List
print([1,2,3,4,5])
print(["satu", "dua", "tiga"])

#tipe data Tuple
print((1,2,3,4,5))
print(("satu", "dua", "tiga"))

#tipe data Dictionary
print({"nama":"Budi", 'umur':20})
#tipe data Dictionary dimasukan ke dalam variable biodata
biodata = {"nama":"Andi", 'umur':21} #proses inisialisasi variable biodata
print(biodata) #proses pencetakan variable biodata yang berisi tipe data Dictionary
print(type(biodata)) #fungsi untuk mengecek jenis tipe data
#akan tampil <class 'dict'> yang berarti dict adalah tipe data dictionary

baris = [1,2,3,4,5]
nilai = baris[2]
print (nilai)